services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
    - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING = true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: placeholder_username
      POSTGRES_PASSWORD: placeholder_password
      POSTGRES_DB: placeholder_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
    # Added health check to ensure PostgreSQL is ready before backend starts.
     # This helps prevent connection errors when Django tries to connect too early.
      test: ["CMD-SHELL", "pg_isready -U placeholder_username"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  pgdata:
